 
=============================================================
The time and date is 03/13/2016 14:50:22
Execution ID: 1457873422985_685100F
Execution folder is /home/tamirk/dt_executions/1457873422985_685100
Log file is in /home/tamirk/cloudify-cosmo/cloudify-deployment-tool/dev/output_1457873422985_685100.log
=============================================================
set_virtualenv: execution id : 1457873422985_685100
Activating virtualenv 'cfy_3_3_1ga_env'
=============================================================
install_cfy: execution id : 1457873422985_685100
/home/tamirk/cfy_versions_root /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
----------------------------------------------------------
Running installCfy.sh ... 
  Required CFY VERSION      : 3.3.1GA
  CFY_MINOR_VERSION is      : 3.3.1
  PLUGINS_MINOR_VERSION is  : 1.3.1
  CFY_GIT_TAG_BRANCH is     : ga
  PLUGINS_GIT_TAG_BRANCH is : ga
Cloudify 3.3.1 ga version already exists (/home/tamirk/cfy_versions_root/3.3.1/ga). -Moving on.
/home/tamirk/cloudify-cosmo/cloudify-deployment-tool
=============================================================
install_cfy_cloud_provider_plugin: execution id : 1457873422985_685100
Cloud Provider                           : datacentred
Cloud user name                          : undefined
Application name                         : xap
Upload Blueprints ?                      : true
Blueprint suffix                         : xap_v13_03_v1
Blueprint file name                      : xap-blueprint-openstack.yaml
Deploy_Application ?                     : true
Deployment name                          : xap_v13_03_v1
CFY_DATA_CENTRED_REGION                  : sal01 ...
CFY_DATA_CENTRED_OS                      : 74ff4015-aee1-4e02-aaa8-1c77b2650394 ...
CFY_DATA_CENTRED_MANAGER_SSH_USER        : undefined ...
CFY_DATA_CENTRED_DATACENTRED_FLAVOR      : undefined ...
CFY_DATA_CENTRED_AGENT_SSH_USER          : undefined ...
CFY_DATA_CENTRED_SERVER_NAME             : server-0-103 ...
CFY_DATA_CENTRED_EXTERNAL_NETWORK_NAME   : undefined ...
CFY_DATA_CENTRED_MANAGEMENT_NETWORK_NAME : mngmnt-net-0-103 ...
CFY_DATA_CENTRED_MANAGEMENT_SUBNET_NAME  : mngmnt-subnet-0-103 ...
CFY_DATA_CENTRED_MANAGEMENT_ROUTER       : mngmnt-router-0-103 ...
CFY_DATA_CENTRED_MANAGER_PORT_NAME       : mngr-port-0-103 ...
CFY_DATA_CENTRED_MANAGER_SECURITY_GROUP  : mngr-sec-grp-0-103 ...
CFY_DATA_CENTRED_AGENT_SECURITY_GROUP    : agent-sec-grp-0-103 ...
CFY_DATA_CENTRED_SSH_KEY_FILE_NAME       : ~/.ssh/cloudify-manager-kp-0-103.pem ...
CFY_DATA_CENTRED_AGENT_PRIVATE_KEY_PATH  : ~/.ssh/cloudify-agent-kp-0-103.pem ...
CFY_DATA_CENTRED_MANAGER_PUBLIC_KEY_NAME : cloudify-manager-public-kp-0-103 ...
CFY_DATA_CENTRED_AGENT_PUBLIC_KEY_NAME   : cloudify-agent-public-kp-0-103 ...
Existing Manager IP address              : 185.43.218.157
Use existing Manager                     : true
Freeze the manager on failure            : false
manager_blueprint_file                   : /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/openstack-manager-blueprint.yaml
manager_blueprint_inputs_file            : /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/openstack-manager-blueprint-inputs.yaml
=============================================================
pre_bootstrap: execution id : 1457873422985_685100
=============================================================
run_bootstrap: execution id : 1457873422985_685100
/home/tamirk/dt_executions/1457873422985_685100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
Cloudify CLI 3.3.1
Cloudify Manager 3.3.1 [ip=185.43.218.157]
Initialization completed successfully
Using an existing Cloudify manager
No Need to bootstrap, running cfy use -t 185.43.218.157
Using management server 185.43.218.157 with port 80
=============================================================
pre_blueprint_upload: execution id : 1457873422985_685100
=============================================================
blueprints_upload: execution id : 1457873422985_685100
Cloning into 'cloudify-deployment-tool-apps'...
Using the repository's master branch
/home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps /home/tamirk/dt_executions/1457873422985_685100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
-------------------------------------------------------------
-------------------------------------------------------------
-------------------------------------------------------------
-------------------------------------------------------------
-------------------------------------------------------------
/home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps/xap /home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps /home/tamirk/dt_executions/1457873422985_685100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
Uploading xap ...
Validating xap-blueprint-openstack.yaml
Blueprint validated successfully
Uploading blueprint xap-blueprint-openstack.yaml to management server 185.43.218.157
Uploaded blueprint, blueprint's id is: xapxap_v13_03_v1
Done uploading xap
/home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps /home/tamirk/dt_executions/1457873422985_685100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
/home/tamirk/dt_executions/1457873422985_685100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
-------------------------------------------------------------
=============================================================
pre_deployment_creation: execution id : 1457873422985_685100
=============================================================
populate_node_templates: execution id : 1457873422985_685100
/home/tamirk/dt_executions/1457873422985_685100
/home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps/xap /home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
Populating node templates of the xap application
The blueprint name will be xapxap_v13_03_v1
Deployment name is xap_v13_03_v1
total 84
-rw-rw-r-- 1 tamirk tamirk 11323 Mar 13 14:51 LICENSE
-rw-rw-r-- 1 tamirk tamirk  3557 Mar 13 14:51 README.md
drwxrwxr-x 2 tamirk tamirk  4096 Mar 13 14:51 butterfly-scripts
drwxrwxr-x 4 tamirk tamirk  4096 Mar 13 14:51 plugins
-rw-rw-r-- 1 tamirk tamirk  5030 Mar 13 14:51 xap-blueprint-commons.yaml
-rw-rw-r-- 1 tamirk tamirk  6972 Mar 13 14:51 xap-blueprint-openstack.yaml
-rw-rw-r-- 1 tamirk tamirk  4613 Mar 13 14:51 xap-blueprint-vagrant.yaml
-rw-rw-r-- 1 tamirk tamirk 11341 Mar 13 14:51 xap-gateway-blueprint-openstack.yaml
-rw-rw-r-- 1 tamirk tamirk  6260 Mar 13 14:51 xap-gateway-blueprint-vagrant.yaml
-rw-rw-r-- 1 tamirk tamirk  1192 Mar 13 14:51 xap-gateway-commons-inputs.yaml
-rw-rw-r-- 1 tamirk tamirk  6972 Mar 13 14:51 xap-gateway-commons.yaml
drwxrwxr-x 2 tamirk tamirk  4096 Mar 13 14:51 xap-scripts
NODE_TEMPLATE_1_NAME is xap_management_vm
-------------------------------------------------------------
create_current_node_template_file: execution id : xap_management_vm
Found the xap_management_vm in line #83
currStatus is 0
NODE_TEMPLATE_1_DATACENTRED_FLAVOR is 8f4b7ae1-b8c2-431f-bb0c-362a5ece0381
Setting the flavor to 8f4b7ae1-b8c2-431f-bb0c-362a5ece0381 in xap_management_vm
NODE_TEMPLATE_1_DATACENTRED_OS is 6c3047c6-17b1-4aaf-a657-9229bb481e50
Setting the image (os) to 6c3047c6-17b1-4aaf-a657-9229bb481e50 in xap_management_vm
NODE_TEMPLATE_1_DATACENTRED_AGENT_USER is ubuntu
Setting the agent ssh user to ubuntu in xap_management_vm
Warning: NODE_TEMPLATE_1_DATACENTRED_MORE_PROPS is unset. - Ignoring it ...
NODE_TEMPLATE_2_NAME is xap_container_vm
-------------------------------------------------------------
create_current_node_template_file: execution id : xap_container_vm
Found the xap_container_vm in line #103
currStatus is 0
NODE_TEMPLATE_2_DATACENTRED_FLAVOR is 8f4b7ae1-b8c2-431f-bb0c-362a5ece0381
Setting the flavor to 8f4b7ae1-b8c2-431f-bb0c-362a5ece0381 in xap_container_vm
NODE_TEMPLATE_2_DATACENTRED_OS is 6c3047c6-17b1-4aaf-a657-9229bb481e50
Setting the image (os) to 6c3047c6-17b1-4aaf-a657-9229bb481e50 in xap_container_vm
NODE_TEMPLATE_2_DATACENTRED_AGENT_USER is ubuntu
Setting the agent ssh user to ubuntu in xap_container_vm
Warning: NODE_TEMPLATE_2_DATACENTRED_MORE_PROPS is unset. - Ignoring it ...
/home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
=============================================================
/home/tamirk/dt_executions/1457873422985_685100/cloudify-deployment-tool-apps
create_deployment: execution id : 1457873422985_685100
Creating new deployment from blueprint xapxap_v13_03_v1 at management server 185.43.218.157
Deployment created, deployment's id is: xap_v13_03_v1
=============================================================
pre_installation: execution id : 1457873422985_685100
=============================================================
installation: execution id : 1457873422985_685100
Executing workflow 'install' on deployment 'xap_v13_03_v1' at management server 185.43.218.157 [timeout=900 seconds]
Deployment environment creation is in progress!
Waiting for create_deployment_environment workflow execution to finish...
2016-03-13T12:51:29 CFY <xap_v13_03_v1> Starting 'create_deployment_environment' workflow execution
2016-03-13T12:51:30 CFY <xap_v13_03_v1> Creating deployment operations worker
2016-03-13T12:51:30 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.create'
2016-03-13T12:51:30 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.create'
2016-03-13T12:51:33 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.create'
2016-03-13T12:51:33 CFY <xap_v13_03_v1> Configuring deployment operations worker
2016-03-13T12:51:33 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.configure'
2016-03-13T12:51:34 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.configure'
2016-03-13T12:51:36 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.configure'
2016-03-13T12:51:36 CFY <xap_v13_03_v1> Starting deployment operations worker
2016-03-13T12:51:37 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.start'
2016-03-13T12:51:37 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.start'
2016-03-13T12:51:42 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.start'
2016-03-13T12:51:42 CFY <xap_v13_03_v1> Installing deployment operations plugins
2016-03-13T12:51:42 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.operations.install_plugins'
2016-03-13T12:51:42 CFY <xap_v13_03_v1> Task started 'cloudify_agent.operations.install_plugins'
2016-03-13T12:51:48 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.operations.install_plugins'
2016-03-13T12:51:57 CFY <xap_v13_03_v1> Stopping deployment operations worker
2016-03-13T12:51:57 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.stop'
2016-03-13T12:51:57 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.stop'
2016-03-13T12:52:02 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.stop'
2016-03-13T12:52:02 CFY <xap_v13_03_v1> Creating deployment workflows worker
2016-03-13T12:52:02 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.create'
2016-03-13T12:52:03 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.create'
2016-03-13T12:52:07 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.create'
2016-03-13T12:52:07 CFY <xap_v13_03_v1> Configuring deployment workflows worker
2016-03-13T12:52:07 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.configure'
2016-03-13T12:52:07 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.configure'
2016-03-13T12:52:10 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.configure'
2016-03-13T12:52:10 CFY <xap_v13_03_v1> Starting deployment workflows worker
2016-03-13T12:52:10 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.installer.operations.start'
2016-03-13T12:52:10 CFY <xap_v13_03_v1> Task started 'cloudify_agent.installer.operations.start'
2016-03-13T12:52:15 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.installer.operations.start'
2016-03-13T12:52:15 CFY <xap_v13_03_v1> Installing deployment workflows plugins
2016-03-13T12:52:15 CFY <xap_v13_03_v1> Sending task 'cloudify_agent.operations.install_plugins'
2016-03-13T12:52:15 CFY <xap_v13_03_v1> Task started 'cloudify_agent.operations.install_plugins'
2016-03-13T12:52:20 CFY <xap_v13_03_v1> Task succeeded 'cloudify_agent.operations.install_plugins'
2016-03-13T12:52:21 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 1]
2016-03-13T12:52:52 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 2]
2016-03-13T12:53:23 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 3]
2016-03-13T12:53:54 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 4]
2016-03-13T12:54:25 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 5]
2016-03-13T12:54:55 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 6]
2016-03-13T12:55:26 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 7]
2016-03-13T12:55:57 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 8]
2016-03-13T12:56:28 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 9]
2016-03-13T12:56:59 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 10]
2016-03-13T12:57:30 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 11]
2016-03-13T12:58:01 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 12]
2016-03-13T12:58:31 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 13]
2016-03-13T12:59:02 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 14]
2016-03-13T12:59:33 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 15]
2016-03-13T13:00:04 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 16]
2016-03-13T13:00:35 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 17]
2016-03-13T13:01:06 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 18]
2016-03-13T13:01:37 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 19]
2016-03-13T13:02:08 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 20]
2016-03-13T13:02:39 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 21]
2016-03-13T13:03:09 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 22]
2016-03-13T13:03:40 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 23]
2016-03-13T13:04:11 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 24]
2016-03-13T13:04:42 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 25]
2016-03-13T13:05:13 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 26]
2016-03-13T13:05:44 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 27]
2016-03-13T13:06:15 CFY <xap_v13_03_v1> Task failed 'cloudify_agent.installer.operations.restart' -> Command '/root/xap_v13_03_v1_workflows/env/bin/python /root/xap_v13_03_v1_workflows/env/bin/cfy-agent daemons restart --name=xap_v13_03_v1_workflows' executed with an error.
code: 1
error: Traceback (most recent call last):
  File "/root/xap_v13_03_v1_workflows/env/bin/cfy-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/xap_v13_03_v1_workflows/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cloudify-rest-client==3.3.1
output: None [attempt 28]
Execution of workflow 'install' for deployment 'xap_v13_03_v1' timed out. * Run 'cfy executions cancel --execution-id 7f27c389-7d10-49b8-a666-ce60aac3c154' to cancel the running workflow.
* Run 'cfy events list --tail --include-logs --execution-id 7f27c389-7d10-49b8-a666-ce60aac3c154' to retrieve the execution's events/logs
Failure in installation
- Aborting
