 
=============================================================
The time and date is 03/04/2016 16:58:06
Execution ID: 1457103486281_864100F
Execution folder is /home/tamirk/dt_executions/1457103486281_864100
Log file is in /home/tamirk/cloudify-cosmo/cloudify-deployment-tool/dev/output_1457103486281_864100.log
=============================================================
set_virtualenv: execution id : 1457103486281_864100
Activating virtualenv 'cfy_3_3_1ga_env'
=============================================================
install_cfy: execution id : 1457103486281_864100
/home/tamirk/cfy_versions_root /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
----------------------------------------------------------
Running installCfy.sh ... 
  Required CFY VERSION      : 3.3.1GA
  CFY_MINOR_VERSION is      : 3.3.1
  PLUGINS_MINOR_VERSION is  : 1.3.1
  CFY_GIT_TAG_BRANCH is     : ga
  PLUGINS_GIT_TAG_BRANCH is : ga
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-dsl-parser.git
Cloning into 'cloudify-dsl-parser'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-dsl-parser /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/3.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 7b5207f... Merge pull request #73 from cloudify-cosmo/CFY-4608-YAML-import-in-blueprint-fails-on-error-code-500
pip installing cloudify-dsl-parser (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-dsl-parser
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-dsl-parser==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-dsl-parser==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-dsl-parser==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): retrying==1.3.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-dsl-parser==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from retrying==1.3.3->cloudify-dsl-parser==3.3.1)
Installing collected packages: cloudify-dsl-parser
  Running setup.py develop for cloudify-dsl-parser
Successfully installed cloudify-dsl-parser-3.3.1
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-rest-client.git
Cloning into 'cloudify-rest-client'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/3.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at a68f55d... Merge pull request #92 from cloudify-cosmo/CFY-3356-suppress-warning-3.3.1
pip installing cloudify-rest-client (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-rest-client==3.3.1)
Installing collected packages: cloudify-rest-client
  Running setup.py develop for cloudify-rest-client
Successfully installed cloudify-rest-client
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-plugins-common.git
Cloning into 'cloudify-plugins-common'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/3.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ee420b8... Merge pull request #186 from cloudify-cosmo/CFY-4465-fix-test-logging
pip installing cloudify-plugins-common (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-rest-client==3.3.1->cloudify-plugins-common==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify-plugins-common==3.3.1)
Installing collected packages: cloudify-plugins-common
  Running setup.py develop for cloudify-plugins-common
Successfully installed cloudify-plugins-common
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-script-plugin.git
Cloning into 'cloudify-script-plugin'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-script-plugin /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 35e1024... Bump version to 1.3.1
pip installing cloudify-script-plugin (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-script-plugin
Requirement already satisfied (use --upgrade to upgrade): cloudify-plugins-common>=3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common (from cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-rest-client==3.3.1->cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify-plugins-common>=3.3.1->cloudify-script-plugin==1.3.1)
Installing collected packages: cloudify-script-plugin
  Running setup.py develop for cloudify-script-plugin
Successfully installed cloudify-script-plugin
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-fabric-plugin.git
Cloning into 'cloudify-fabric-plugin'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 9c0dc40... Merge pull request #26 from cloudify-cosmo/CFY-4645-fabric-forward-agent-false
pip installing cloudify-fabric-plugin (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin
Requirement already satisfied (use --upgrade to upgrade): cloudify-plugins-common>=3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common (from cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): fabric==1.8.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.8.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): paramiko<1.13,>=1.10 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from fabric==1.8.3->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-rest-client==3.3.1->cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify-plugins-common>=3.3.1->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): ecdsa in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from paramiko<1.13,>=1.10->fabric==1.8.3->cloudify-fabric-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pycrypto!=2.4,>=2.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from paramiko<1.13,>=1.10->fabric==1.8.3->cloudify-fabric-plugin==1.3.1)
Installing collected packages: cloudify-fabric-plugin
  Running setup.py develop for cloudify-fabric-plugin
Successfully installed cloudify-fabric-plugin
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-cli.git
Cloning into 'cloudify-cli'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/3.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at b97e141... Merge pull request #260 from cloudify-cosmo/CFY-4443-Bootstrap-fails-on-network-issues-when-uploading
pip installing cloudify-cli (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli
Requirement already satisfied (use --upgrade to upgrade): cloudify-plugins-common==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-dsl-parser==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-dsl-parser (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-script-plugin==1.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-script-plugin (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.10 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): argcomplete==0.7.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): fabric==1.8.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): PrettyTable<0.8,>=0.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): retrying==1.3.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common==3.3.1->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-rest-client==3.3.1->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): paramiko<1.13,>=1.10 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from fabric==1.8.3->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from retrying==1.3.3->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): ecdsa in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from paramiko<1.13,>=1.10->fabric==1.8.3->cloudify==3.3.1)
Requirement already satisfied (use --upgrade to upgrade): pycrypto!=2.4,>=2.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from paramiko<1.13,>=1.10->fabric==1.8.3->cloudify==3.3.1)
Installing collected packages: cloudify
  Running setup.py develop for cloudify
Successfully installed cloudify
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-openstack-plugin.git
Cloning into 'cloudify-openstack-plugin'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-openstack-plugin /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 12770c0... Merge pull request #103 from cloudify-cosmo/CFY-2834-description-property-for-security-group
pip installing cloudify-openstack-plugin (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-openstack-plugin
Requirement already satisfied (use --upgrade to upgrade): cloudify-plugins-common>=3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common (from cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): python-novaclient==2.26.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): python-keystoneclient==1.6.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): python-neutronclient==2.6.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): python-cinderclient==1.2.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): IPy==0.81 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): oslo.serialization>=1.4.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): oslo.i18n>=1.5.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pbr<2.0,>=0.11 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): PrettyTable<0.8,>=0.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): iso8601>=0.1.9 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): oslo.utils>=1.4.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): simplejson>=2.2.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): stevedore>=1.3.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-keystoneclient==1.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): netaddr>=0.7.12 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-keystoneclient==1.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): oslo.config>=1.11.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-keystoneclient==1.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cliff>=1.10.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-neutronclient==2.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify-plugins-common>=3.3.1->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from oslo.serialization>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2013.6 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from oslo.serialization>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): funcsigs>=0.4 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from oslo.utils>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): monotonic>=0.6 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from oslo.utils>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): debtcollector>=1.2.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from oslo.utils>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): netifaces>=0.10.4 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from oslo.utils>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cmd2>=0.6.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cliff>=1.10.0->python-neutronclient==2.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=2.0.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cliff>=1.10.0->python-neutronclient==2.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cliff>=1.10.0->python-neutronclient==2.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): unicodecsv>=0.8.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cliff>=1.10.0->python-neutronclient==2.6.0->cloudify-openstack-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): wrapt>=1.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from debtcollector>=1.2.0->oslo.utils>=1.4.0->python-novaclient==2.26.0->cloudify-openstack-plugin==1.3.1)
Installing collected packages: cloudify-openstack-plugin
  Running setup.py develop for cloudify-openstack-plugin
Successfully installed cloudify-openstack-plugin
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-aws-plugin.git
Cloning into 'cloudify-aws-plugin'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-aws-plugin /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 6024051... Merge pull request #121 from cloudify-cosmo/CFY-4711-support-subtree-auth
pip installing cloudify-aws-plugin (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-aws-plugin
Requirement already satisfied (use --upgrade to upgrade): cloudify-plugins-common>=3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common (from cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): boto==2.38.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-rest-client==3.3.1->cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify-plugins-common>=3.3.1->cloudify-aws-plugin==1.3.1)
Installing collected packages: cloudify-aws-plugin
  Running setup.py develop for cloudify-aws-plugin
Successfully installed cloudify-aws-plugin
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-azure-plugin.git
Cloning into 'cloudify-azure-plugin'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Until the GA release, we're using tag 'working331ga' for cloudify-azure-plugin
Note: checking out 'tags/331_ga_march_04_2016'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e83c280... March 4th - push : 4
pip installing cloudify-azure-plugin (-e .)...
Obtaining file:///home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin
Requirement already satisfied (use --upgrade to upgrade): cloudify-plugins-common>=3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common (from cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): lockfile in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): cloudify-rest-client==3.3.1 in /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client (from cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): pika==0.9.14 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): networkx==1.8.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): proxy-tools==0.1.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.7.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-servicemanagement-legacy==0.20.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt==0.20.2 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-storage==0.20.3 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-servicebus==0.20.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from jinja2==2.7.2->cloudify-plugins-common>=3.3.1->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-common in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-servicemanagement-legacy==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-compute==0.20.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-mgmt==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-resource==0.20.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-mgmt==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-network==0.20.1 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-mgmt==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-storage==0.20.0 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-mgmt==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): futures in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-storage==0.20.3->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-storage==0.20.3->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-nspkg in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-storage==0.20.3->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-common in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-mgmt-compute==0.20.1->azure-mgmt==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from python-dateutil->azure-storage==0.20.3->azure->cloudify-azure-plugin==1.3.1)
Requirement already satisfied (use --upgrade to upgrade): azure-mgmt-nspkg in /home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/lib/python2.7/site-packages (from azure-mgmt-common->azure-mgmt-compute==0.20.1->azure-mgmt==0.20.2->azure->cloudify-azure-plugin==1.3.1)
Installing collected packages: cloudify-azure-plugin
  Running setup.py develop for cloudify-azure-plugin
Successfully installed cloudify-azure-plugin-1.3.1
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-manager-blueprints.git
Cloning into 'cloudify-manager-blueprints'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
Note: checking out 'tags/3.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 89ad3ab... fixing cloudify_resources_url in inputs.yaml
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
git clone https://github.com/cloudify-cosmo/cloudify-nodecellar-example.git
Cloning into 'cloudify-nodecellar-example'...
/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-nodecellar-example /home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
cloudify-nodecellar-example doesn't need pip ...
Note: checking out 'tags/3.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 1906ed6... Bump version to 3.3.1
/home/tamirk/cfy_versions_root/3.3.1/ga /home/tamirk/cfy_versions_root
argcomplete (0.7.1)
azure (1.0.3)
azure-common (1.0.0)
azure-mgmt (0.20.2)
azure-mgmt-common (0.20.0)
azure-mgmt-compute (0.20.1)
azure-mgmt-network (0.20.1)
azure-mgmt-nspkg (1.0.0)
azure-mgmt-resource (0.20.1)
azure-mgmt-storage (0.20.0)
azure-nspkg (1.0.0)
azure-servicebus (0.20.1)
azure-servicemanagement-legacy (0.20.2)
azure-storage (0.20.3)
Babel (2.2.0)
boto (2.38.0)
bottle (0.12.7)
cliff (1.16.0)
cloudify (3.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-cli)
cloudify-aws-plugin (1.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-aws-plugin)
cloudify-azure-plugin (1.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin)
cloudify-dsl-parser (3.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-dsl-parser)
cloudify-fabric-plugin (1.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin)
cloudify-openstack-plugin (1.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-openstack-plugin)
cloudify-plugins-common (3.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common)
cloudify-rest-client (3.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-rest-client)
cloudify-script-plugin (1.3.1, /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-script-plugin)
cmd2 (0.6.8)
colorama (0.3.3)
debtcollector (1.3.0)
ecdsa (0.13)
Fabric (1.8.3)
funcsigs (0.4)
futures (3.0.4)
IPy (0.81)
iso8601 (0.1.11)
itsdangerous (0.24)
Jinja2 (2.7.2)
lockfile (0.12.2)
MarkupSafe (0.23)
monotonic (0.6)
msgpack-python (0.4.7)
netaddr (0.7.18)
netifaces (0.10.4)
networkx (1.8.1)
oslo.config (3.6.0)
oslo.i18n (3.3.0)
oslo.serialization (2.3.0)
oslo.utils (3.5.0)
paramiko (1.12.4)
pbr (1.8.1)
pika (0.9.14)
pip (7.1.2)
prettytable (0.7.2)
proxy-tools (0.1.0)
pycrypto (2.6.1)
pyparsing (2.1.0)
python-cinderclient (1.2.2)
python-dateutil (2.4.2)
python-keystoneclient (1.6.0)
python-neutronclient (2.6.0)
python-novaclient (2.26.0)
pytz (2015.7)
PyYAML (3.10)
requests (2.7.0)
retrying (1.3.3)
setuptools (18.2)
simplejson (3.8.1)
six (1.10.0)
stevedore (1.11.0)
unicodecsv (0.14.1)
wheel (0.24.0)
wrapt (1.10.6)
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Cloudify CLI 3.3.1
/home/tamirk/cfy_versions_root
End of installCfy.sh
----------------------------------------------------------
/home/tamirk/cloudify-cosmo/cloudify-deployment-tool
=============================================================
install_cfy_cloud_provider_plugin: execution id : 1457103486281_864100
Cloud Provider                           : azure
Cloud user name                          : undefined
Application name                         : undefined
Blueprint name                           : undefined
Blueprint file name                      : undefined
Manager VM location                      : undefined
Manager VM size                          : undefined
Manager VM prefix                        : undefined
Manager VM SSH username                  : undefined
Manager VM operating system              : undefined
Manager VM resource group                : undefined
Manager VM uses existing resource group  : undefined
Manager VM storage account               : undefined
Manager VM uses existing storage account : undefined
Manager VM Vnet                          : undefined
Manager VM uses existing Vnet            : undefined
Manager VM subnet                        : undefined
Manager VM uses existing subnet          : undefined
Manager VM security group                : undefined
Manager VM uses existing security group  : undefined
Existing Manager IP address              : undefined
Use existing Manager                     : undefined
Freeze the manager on failure            : undefined
manager_blueprint_file                   : /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/azure-manager-blueprint.yaml
manager_blueprint_inputs_file            : /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/azure-manager-blueprint-inputs.yaml
=============================================================
pre_bootstrap: execution id : 1457103486281_864100
=============================================================
run_bootstrap: execution id : 1457103486281_864100
/home/tamirk/dt_executions/1457103486281_864100 /home/tamirk/cloudify-cosmo/cloudify-deployment-tool
Cloudify CLI 3.3.1
Initialization completed successfully
-------------------------------------------------------------
azure_init_bootstrap: execution id : 1457103486281_864100
Running: cfy bootstrap -p /home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-manager-blueprints/azure-manager-blueprint.yaml -i current_azure_inputs_file.yaml
executing bootstrap validation
2016-03-04 17:00:11 CFY <manager> Starting 'execute_operation' workflow execution
2016-03-04 17:00:11 CFY <manager> [riemann_a1462] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [azure_token_c8251] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_custom_script_697e0] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_nic_24958] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [java_runtime_6f085] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [webui_801e7] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_subnet_748fc] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [logstash_bf26f] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_storage_account_f3623] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [rabbitmq_590c0] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [rest_service_30c0e] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [python_runtime_8310c] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [mgmt_worker_4f91c] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_host_59eca] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_public_ip_1a7dc] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [nginx_9f3c0] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_configuration_c9613] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_vnet_a6a51] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_resource_group_c69f8] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [elasticsearch_8ec7a] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [amqp_influx_ff54c] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_data_disk_edba1] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [influxdb_12634] Starting operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_resource_group_c69f8.creation] Sending task 'azurecloudify.resourcegroup.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_storage_account_f3623.creation] Sending task 'azurecloudify.storageaccount.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_host_59eca.creation] Sending task 'azurecloudify.server.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_data_disk_edba1.creation] Sending task 'azurecloudify.datadisk.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_vnet_a6a51.creation] Sending task 'azurecloudify.vnet.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_nic_24958.creation] Sending task 'azurecloudify.nic.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_subnet_748fc.creation] Sending task 'azurecloudify.subnet.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_public_ip_1a7dc.creation] Sending task 'azurecloudify.publicip.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_custom_script_697e0.creation] Sending task 'azurecloudify.extensions.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_resource_group_c69f8.creation] Task started 'azurecloudify.resourcegroup.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_resource_group_c69f8.creation] Task succeeded 'azurecloudify.resourcegroup.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_storage_account_f3623.creation] Task started 'azurecloudify.storageaccount.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_storage_account_f3623.creation] Task succeeded 'azurecloudify.storageaccount.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_host_59eca.creation] Task started 'azurecloudify.server.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_host_59eca.creation] Task succeeded 'azurecloudify.server.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_data_disk_edba1.creation] Task started 'azurecloudify.datadisk.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_data_disk_edba1.creation] Task succeeded 'azurecloudify.datadisk.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_vnet_a6a51.creation] Task started 'azurecloudify.vnet.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_vnet_a6a51.creation] Task succeeded 'azurecloudify.vnet.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_nic_24958.creation] Task started 'azurecloudify.nic.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_nic_24958.creation] Task succeeded 'azurecloudify.nic.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_subnet_748fc.creation] Task started 'azurecloudify.subnet.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_subnet_748fc.creation] Task succeeded 'azurecloudify.subnet.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_public_ip_1a7dc.creation] Task started 'azurecloudify.publicip.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_public_ip_1a7dc.creation] Task succeeded 'azurecloudify.publicip.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_custom_script_697e0.creation] Task started 'azurecloudify.extensions.creation_validation'
2016-03-04 17:00:11 CFY <manager> [manager_custom_script_697e0.creation] Task succeeded 'azurecloudify.extensions.creation_validation'
2016-03-04 17:00:11 CFY <manager> [java_runtime_6f085] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [rabbitmq_590c0] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_configuration_c9613] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_subnet_748fc] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_data_disk_edba1] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_vnet_a6a51] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [influxdb_12634] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [mgmt_worker_4f91c] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [azure_token_c8251] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_host_59eca] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [amqp_influx_ff54c] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [python_runtime_8310c] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_nic_24958] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_storage_account_f3623] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [rest_service_30c0e] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [nginx_9f3c0] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_public_ip_1a7dc] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [logstash_bf26f] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [webui_801e7] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_resource_group_c69f8] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [manager_custom_script_697e0] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [riemann_a1462] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> [elasticsearch_8ec7a] Finished operation cloudify.interfaces.validation.creation
2016-03-04 17:00:11 CFY <manager> 'execute_operation' workflow execution succeeded
bootstrap validation completed successfully
executing bootstrap
2016-03-04 17:00:22 CFY <manager> Starting 'install' workflow execution
2016-03-04 17:00:22 CFY <manager> [azure_token_066f9] Creating node
2016-03-04 17:00:22 CFY <manager> [azure_token_066f9.create] Sending task 'azurecloudify.auth.initialize'
2016-03-04 17:00:22 CFY <manager> [azure_token_066f9.create] Task started 'azurecloudify.auth.initialize'
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: initialize: subscription_id is undefined
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: initialize: location is undefined
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: tenant_id is undefined
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: client_id is undefined
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: aad_password is undefined
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: grant_type is client_credentials
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: username is 
2016-03-04 17:00:22 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: password is 
2016-03-04 17:00:23 LOG <manager> [azure_token_066f9.create] ERROR: Exception raised on operation [azurecloudify.auth.initialize] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 20, in initialize
    generate_token(use_client_file=True, start_retry_interval=30, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 25, in generate_token
    token, token_expires = _get_token_value_expiry(endpoints, payload)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 46, in _get_token_value_expiry
    token = response['access_token']
KeyError: 'access_token'
2016-03-04 17:00:23 CFY <manager> [azure_token_066f9.create] Task failed 'azurecloudify.auth.initialize' -> 'access_token' [attempt 1/6]
2016-03-04 17:00:53 CFY <manager> [azure_token_066f9.create] Sending task 'azurecloudify.auth.initialize' [attempt 2/6]
2016-03-04 17:00:53 CFY <manager> [azure_token_066f9.create] Task started 'azurecloudify.auth.initialize' [attempt 2/6]
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: initialize: subscription_id is undefined
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: initialize: location is undefined
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: tenant_id is undefined
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: client_id is undefined
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: aad_password is undefined
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: grant_type is client_credentials
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: username is 
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: password is 
2016-03-04 17:00:53 LOG <manager> [azure_token_066f9.create] ERROR: Exception raised on operation [azurecloudify.auth.initialize] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 20, in initialize
    generate_token(use_client_file=True, start_retry_interval=30, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 25, in generate_token
    token, token_expires = _get_token_value_expiry(endpoints, payload)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 46, in _get_token_value_expiry
    token = response['access_token']
KeyError: 'access_token'
2016-03-04 17:00:53 CFY <manager> [azure_token_066f9.create] Task failed 'azurecloudify.auth.initialize' -> 'access_token' [attempt 2/6]
2016-03-04 17:01:23 CFY <manager> [azure_token_066f9.create] Sending task 'azurecloudify.auth.initialize' [attempt 3/6]
2016-03-04 17:01:24 CFY <manager> [azure_token_066f9.create] Task started 'azurecloudify.auth.initialize' [attempt 3/6]
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: initialize: subscription_id is undefined
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: initialize: location is undefined
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: tenant_id is undefined
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: client_id is undefined
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: aad_password is undefined
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: grant_type is client_credentials
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: username is 
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: password is 
2016-03-04 17:01:24 LOG <manager> [azure_token_066f9.create] ERROR: Exception raised on operation [azurecloudify.auth.initialize] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 20, in initialize
    generate_token(use_client_file=True, start_retry_interval=30, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 25, in generate_token
    token, token_expires = _get_token_value_expiry(endpoints, payload)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 46, in _get_token_value_expiry
    token = response['access_token']
KeyError: 'access_token'
2016-03-04 17:01:24 CFY <manager> [azure_token_066f9.create] Task failed 'azurecloudify.auth.initialize' -> 'access_token' [attempt 3/6]
2016-03-04 17:01:54 CFY <manager> [azure_token_066f9.create] Sending task 'azurecloudify.auth.initialize' [attempt 4/6]
2016-03-04 17:01:54 CFY <manager> [azure_token_066f9.create] Task started 'azurecloudify.auth.initialize' [attempt 4/6]
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: initialize: subscription_id is undefined
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: initialize: location is undefined
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: tenant_id is undefined
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: client_id is undefined
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: aad_password is undefined
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: grant_type is client_credentials
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: username is 
2016-03-04 17:01:54 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: password is 
2016-03-04 17:01:55 LOG <manager> [azure_token_066f9.create] ERROR: Exception raised on operation [azurecloudify.auth.initialize] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 20, in initialize
    generate_token(use_client_file=True, start_retry_interval=30, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 25, in generate_token
    token, token_expires = _get_token_value_expiry(endpoints, payload)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 46, in _get_token_value_expiry
    token = response['access_token']
KeyError: 'access_token'
2016-03-04 17:01:55 CFY <manager> [azure_token_066f9.create] Task failed 'azurecloudify.auth.initialize' -> 'access_token' [attempt 4/6]
2016-03-04 17:02:25 CFY <manager> [azure_token_066f9.create] Sending task 'azurecloudify.auth.initialize' [attempt 5/6]
2016-03-04 17:02:25 CFY <manager> [azure_token_066f9.create] Task started 'azurecloudify.auth.initialize' [attempt 5/6]
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: initialize: subscription_id is undefined
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: initialize: location is undefined
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: tenant_id is undefined
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: client_id is undefined
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: aad_password is undefined
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: grant_type is client_credentials
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: username is 
2016-03-04 17:02:25 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: password is 
2016-03-04 17:02:26 LOG <manager> [azure_token_066f9.create] ERROR: Exception raised on operation [azurecloudify.auth.initialize] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 20, in initialize
    generate_token(use_client_file=True, start_retry_interval=30, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 25, in generate_token
    token, token_expires = _get_token_value_expiry(endpoints, payload)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 46, in _get_token_value_expiry
    token = response['access_token']
KeyError: 'access_token'
2016-03-04 17:02:26 CFY <manager> [azure_token_066f9.create] Task failed 'azurecloudify.auth.initialize' -> 'access_token' [attempt 5/6]
2016-03-04 17:02:56 CFY <manager> [azure_token_066f9.create] Sending task 'azurecloudify.auth.initialize' [attempt 6/6]
2016-03-04 17:02:56 CFY <manager> [azure_token_066f9.create] Task started 'azurecloudify.auth.initialize' [attempt 6/6]
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: initialize: subscription_id is undefined
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: initialize: location is undefined
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: tenant_id is undefined
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: client_id is undefined
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: aad_password is undefined
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: grant_type is client_credentials
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: username is 
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] INFO: _get_payload_endpoints: password is 
2016-03-04 17:02:56 LOG <manager> [azure_token_066f9.create] ERROR: Exception raised on operation [azurecloudify.auth.initialize] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 20, in initialize
    generate_token(use_client_file=True, start_retry_interval=30, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 25, in generate_token
    token, token_expires = _get_token_value_expiry(endpoints, payload)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 46, in _get_token_value_expiry
    token = response['access_token']
KeyError: 'access_token'
2016-03-04 17:02:56 CFY <manager> [azure_token_066f9.create] Task failed 'azurecloudify.auth.initialize' -> 'access_token' [attempt 6/6]
2016-03-04 17:02:56 CFY <manager> 'install' workflow execution failed: Workflow failed: Task failed 'azurecloudify.auth.initialize' -> 'access_token'
bootstrap failed! (Workflow failed: Task failed 'azurecloudify.auth.initialize' -> 'access_token')
executing teardown due to failed bootstrap

Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.

Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.
2016-03-04 17:02:57 CFY <manager> Starting 'uninstall' workflow execution
2016-03-04 17:02:57 CFY <manager> [mgmt_worker_7a57b] Stopping node
2016-03-04 17:02:57 CFY <manager> [riemann_ce4b8] Stopping node
2016-03-04 17:02:57 CFY <manager> [webui_93e4b] Stopping node
2016-03-04 17:02:57 CFY <manager> [logstash_7f585] Stopping node
2016-03-04 17:02:57 CFY <manager> [amqp_influx_f35ea] Stopping node
2016-03-04 17:02:57 CFY <manager> [manager_custom_script_bb7d8] Stopping node
2016-03-04 17:02:57 CFY <manager> [mgmt_worker_7a57b.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 CFY <manager> [riemann_ce4b8.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 CFY <manager> [logstash_7f585.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 CFY <manager> [webui_93e4b.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 CFY <manager> [amqp_influx_f35ea.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 CFY <manager> [mgmt_worker_7a57b.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 LOG <manager> [mgmt_worker_7a57b.stop] INFO: preparing fabric environment...
2016-03-04 17:02:57 LOG <manager> [mgmt_worker_7a57b.stop] INFO: environment prepared successfully
2016-03-04 17:02:57 LOG <manager> [mgmt_worker_7a57b.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:57 CFY <manager> [mgmt_worker_7a57b.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:57 CFY <manager> [riemann_ce4b8.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 LOG <manager> [riemann_ce4b8.stop] INFO: preparing fabric environment...
2016-03-04 17:02:57 LOG <manager> [riemann_ce4b8.stop] INFO: environment prepared successfully
2016-03-04 17:02:57 LOG <manager> [riemann_ce4b8.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/
Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.

Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.
local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:57 CFY <manager> [riemann_ce4b8.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:57 CFY <manager> [logstash_7f585.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 LOG <manager> [logstash_7f585.stop] INFO: preparing fabric environment...
2016-03-04 17:02:57 LOG <manager> [logstash_7f585.stop] INFO: environment prepared successfully
2016-03-04 17:02:57 LOG <manager> [logstash_7f585.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:57 CFY <manager> [logstash_7f585.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:57 CFY <manager> [webui_93e4b.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 LOG <manager> [webui_93e4b.stop] INFO: preparing fabric environment...
2016-03-04 17:02:57 LOG <manager> [webui_93e4b.stop] INFO: environment prepared successfully
2016-03-04 17:02:57 LOG <manager> [webui_93e4b.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connecti
Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.

Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.
on string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:57 CFY <manager> [webui_93e4b.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:57 CFY <manager> [amqp_influx_f35ea.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:57 LOG <manager> [amqp_influx_f35ea.stop] INFO: preparing fabric environment...
2016-03-04 17:02:57 LOG <manager> [amqp_influx_f35ea.stop] INFO: environment prepared successfully
2016-03-04 17:02:57 LOG <manager> [amqp_influx_f35ea.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:57 CFY <manager> [amqp_influx_f35ea.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:58 CFY <manager> [logstash_7f585] Deleting node
2016-03-04 17:02:58 CFY <manager> [riemann_ce4b8] Deleting node
2016-03-04 17:02:58 CFY <manager> [manager_custom_script_bb7d8] Deleting node
2016-03-04 17:02:58 CFY <manager> [mgmt_worker_7a57b] Deleting node
2016-03-04 17:02:58 CFY <manager> [webui_93e4b] Deleting node
2016-03-04 17:02:58 CFY <manager> [amqp_influx_f35ea] Deleting node
2016-03-04 17:02:58 CFY <manager> [influxdb_3925e] Stopping node
2016-03-04 17:02:58 CFY <manager> [rest_service_e01ab] Stopping node
2016-03-04 17:02:58 CFY <manager> [nginx_115a8] Stopping node
2016-03-04 17:02:58 CFY <manager> [rest_service_e01ab.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:58 CFY <manager> [influxdb_3925e.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:58 CFY <manager> [rest_service_e01ab.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:58 LOG <manager> [rest_service_e01ab.stop] INFO: preparing fabric environment...
2016-03-04 17:02:58 LOG <manager> [rest_service_e01ab.stop] INFO: environment prepared successfully
2016-03-04 17:02:58 LOG <manager> [rest_service_e01ab.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.

Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.

    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:58 CFY <manager> [rest_service_e01ab.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:58 CFY <manager> [influxdb_3925e.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:58 LOG <manager> [influxdb_3925e.stop] INFO: preparing fabric environment...
2016-03-04 17:02:58 LOG <manager> [influxdb_3925e.stop] INFO: environment prepared successfully
2016-03-04 17:02:58 LOG <manager> [influxdb_3925e.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:58 CFY <manager> [influxdb_3925e.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:58 CFY <manager> [nginx_115a8.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:58 CFY <manager> [nginx_115a8.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:58 LOG <manager> [nginx_115a8.stop] INFO: preparing fabric environment...
2016-03-04 17:02:58 LOG <manager> [nginx_115a8.stop] INFO: environment prepared successfully
2016-03-04 17:02:58 LOG <manager> [nginx_115a8.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
 
Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.

Fatal error: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True

Aborting.
 File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:58 CFY <manager> [nginx_115a8.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:59 CFY <manager> [influxdb_3925e] Deleting node
2016-03-04 17:02:59 CFY <manager> [rest_service_e01ab] Deleting node
2016-03-04 17:02:59 CFY <manager> [nginx_115a8] Deleting node
2016-03-04 17:02:59 CFY <manager> [python_runtime_77c95] Stopping node
2016-03-04 17:02:59 CFY <manager> [elasticsearch_23df6] Stopping node
2016-03-04 17:02:59 CFY <manager> [rabbitmq_15dcd] Stopping node
2016-03-04 17:02:59 CFY <manager> [manager_configuration_18c68] Stopping node
2016-03-04 17:02:59 CFY <manager> [rabbitmq_15dcd.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:59 CFY <manager> [elasticsearch_23df6.stop] Sending task 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:59 CFY <manager> [rabbitmq_15dcd.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:59 LOG <manager> [rabbitmq_15dcd.stop] INFO: preparing fabric environment...
2016-03-04 17:02:59 LOG <manager> [rabbitmq_15dcd.stop] INFO: environment prepared successfully
2016-03-04 17:02:59 LOG <manager> [rabbitmq_15dcd.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:59 CFY <manager> [rabbitmq_15dcd.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:02:59 CFY <manager> [elasticsearch_23df6.stop] Task started 'fabric_plugin.tasks.run_script'
2016-03-04 17:02:59 LOG <manager> [elasticsearch_23df6.stop] INFO: preparing fabric environment...
2016-03-04 17:02:59 LOG <manager> [elasticsearch_23df6.stop] INFO: environment prepared successfully
2016-03-04 17:02:59 LOG <manager> [elasticsearch_23df6.stop] ERROR: Exception raised on operation [fabric_plugin.tasks.run_script] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-fabric-plugin/fabric_plugin/tasks.py", line 152, in run_script
    if not fabric_files.exists(remote_ctx_path):
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/network.py", line 635, in host_prompting_wrapper
    handle_prompt_abort("the target host connection string")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 151, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/tamirk/deployment_tool_envs/cfy_3_3_1ga_env/local/lib/python2.7/site-packages/fabric/utils.py", line 32, in abort
    raise env.abort_exception(msg)
FabricTaskError: Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True
2016-03-04 17:02:59 CFY <manager> [elasticsearch_23df6.stop] Task failed 'fabric_plugin.tasks.run_script' -> Needed to prompt for the target host connection string (host: None), but abort-on-prompts was set to True [attempt 1/6]
2016-03-04 17:03:00 CFY <manager> [rabbitmq_15dcd] Deleting node
2016-03-04 17:03:00 CFY <manager> [python_runtime_77c95] Deleting node
2016-03-04 17:03:00 CFY <manager> [elasticsearch_23df6] Deleting node
2016-03-04 17:03:00 CFY <manager> [manager_configuration_18c68] Deleting node
2016-03-04 17:03:00 CFY <manager> [java_runtime_cc665] Stopping node
2016-03-04 17:03:01 CFY <manager> [java_runtime_cc665] Deleting node
2016-03-04 17:03:01 CFY <manager> [manager_host_6e309] Stopping node
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309.stop] Sending task 'azurecloudify.server.stop_vm'
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309.stop] Task started 'azurecloudify.server.stop_vm'
2016-03-04 17:03:02 LOG <manager> [manager_host_6e309.stop] ERROR: Exception raised on operation [azurecloudify.server.stop_vm] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/server.py", line 110, in stop_vm
    stop_a_vm()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/server.py", line 114, in stop_a_vm
    headers, location, subscription_id = auth.get_credentials()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 160, in get_credentials
    subscription_id = current_instance.runtime_properties['subscription_id']
KeyError: 'subscription_id'
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309.stop] Task failed 'azurecloudify.server.stop_vm' -> 'subscription_id' [attempt 1/6]
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309] Deleting node
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309.delete] Sending task 'azurecloudify.server.delete_virtual_machine'
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309.delete] Task started 'azurecloudify.server.delete_virtual_machine'
2016-03-04 17:03:02 LOG <manager> [manager_host_6e309.delete] ERROR: Exception raised on operation [azurecloudify.server.delete_virtual_machine] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/server.py", line 130, in delete_virtual_machine
    _delete_vm_and_disks(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/server.py", line 123, in _delete_vm_and_disks
    delete_current_virtual_machine(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/server.py", line 139, in delete_current_virtual_machine
    resource_group_name = ctx.instance.runtime_properties[constants.RESOURCE_GROUP_KEY]
KeyError: 'resource_group_key_name'
2016-03-04 17:03:02 CFY <manager> [manager_host_6e309.delete] Task failed 'azurecloudify.server.delete_virtual_machine' -> 'resource_group_key_name' [attempt 1/6]
2016-03-04 17:03:03 CFY <manager> [manager_nic_6a50a] Stopping node
2016-03-04 17:03:03 CFY <manager> [manager_data_disk_fedca] Stopping node
2016-03-04 17:03:03 CFY <manager> [manager_nic_6a50a] Deleting node
2016-03-04 17:03:03 CFY <manager> [manager_data_disk_fedca] Deleting node
2016-03-04 17:03:03 CFY <manager> [manager_nic_6a50a.delete] Sending task 'azurecloudify.nic.delete_nic'
2016-03-04 17:03:03 CFY <manager> [manager_nic_6a50a.delete] Task started 'azurecloudify.nic.delete_nic'
2016-03-04 17:03:03 LOG <manager> [manager_nic_6a50a.delete] ERROR: Exception raised on operation [azurecloudify.nic.delete_nic] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/nic.py", line 150, in delete_nic
    delete_a_nic(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/nic.py", line 155, in delete_a_nic
    delete_current_nic(start_retry_interval)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/nic.py", line 164, in delete_current_nic
    headers, location, subscription_id = auth.get_credentials()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 160, in get_credentials
    subscription_id = current_instance.runtime_properties['subscription_id']
KeyError: 'subscription_id'
2016-03-04 17:03:03 CFY <manager> [manager_nic_6a50a.delete] Task failed 'azurecloudify.nic.delete_nic' -> 'subscription_id' [attempt 1/6]
2016-03-04 17:03:04 CFY <manager> [manager_public_ip_d8cc5] Stopping node
2016-03-04 17:03:04 CFY <manager> [manager_storage_account_8f504] Stopping node
2016-03-04 17:03:04 CFY <manager> [manager_public_ip_d8cc5] Deleting node
2016-03-04 17:03:04 CFY <manager> [manager_storage_account_8f504] Deleting node
2016-03-04 17:03:04 CFY <manager> [manager_storage_account_8f504.delete] Sending task 'azurecloudify.storageaccount.delete_storage_account'
2016-03-04 17:03:04 CFY <manager> [manager_public_ip_d8cc5.delete] Sending task 'azurecloudify.publicip.delete_public_ip'
2016-03-04 17:03:04 CFY <manager> [manager_storage_account_8f504.delete] Task started 'azurecloudify.storageaccount.delete_storage_account'
2016-03-04 17:03:04 LOG <manager> [manager_storage_account_8f504.delete] ERROR: Exception raised on operation [azurecloudify.storageaccount.delete_storage_account] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/storageaccount.py", line 71, in delete_storage_account
    status_code = delete_current_storage_account(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/storageaccount.py", line 82, in delete_current_storage_account
    resource_group_name = ctx.instance.runtime_properties[constants.RESOURCE_GROUP_KEY]
KeyError: 'resource_group_key_name'
2016-03-04 17:03:04 CFY <manager> [manager_storage_account_8f504.delete] Task failed 'azurecloudify.storageaccount.delete_storage_account' -> 'resource_group_key_name' [attempt 1/6]
2016-03-04 17:03:04 CFY <manager> [manager_public_ip_d8cc5.delete] Task started 'azurecloudify.publicip.delete_public_ip'
2016-03-04 17:03:04 LOG <manager> [manager_public_ip_d8cc5.delete] ERROR: Exception raised on operation [azurecloudify.publicip.delete_public_ip] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/publicip.py", line 70, in delete_public_ip
    delete_current_public_ip(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/publicip.py", line 80, in delete_current_public_ip
    headers, location, subscription_id = auth.get_credentials()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 160, in get_credentials
    subscription_id = current_instance.runtime_properties['subscription_id']
KeyError: 'subscription_id'
2016-03-04 17:03:04 CFY <manager> [manager_public_ip_d8cc5.delete] Task failed 'azurecloudify.publicip.delete_public_ip' -> 'subscription_id' [attempt 1/6]
2016-03-04 17:03:05 CFY <manager> [manager_vnet_b91ef] Stopping node
2016-03-04 17:03:05 CFY <manager> [manager_vnet_b91ef] Deleting node
2016-03-04 17:03:05 CFY <manager> [manager_vnet_b91ef.delete] Sending task 'azurecloudify.vnet.delete_vnet'
2016-03-04 17:03:05 CFY <manager> [manager_vnet_b91ef.delete] Task started 'azurecloudify.vnet.delete_vnet'
2016-03-04 17:03:05 LOG <manager> [manager_vnet_b91ef.delete] ERROR: Exception raised on operation [azurecloudify.vnet.delete_vnet] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/vnet.py", line 70, in delete_vnet
    delete_current_vnet(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/vnet.py", line 80, in delete_current_vnet
    resource_group_name = ctx.instance.runtime_properties[constants.RESOURCE_GROUP_KEY]
KeyError: 'resource_group_key_name'
2016-03-04 17:03:05 CFY <manager> [manager_vnet_b91ef.delete] Task failed 'azurecloudify.vnet.delete_vnet' -> 'resource_group_key_name' [attempt 1/6]
2016-03-04 17:03:06 CFY <manager> [manager_subnet_8f2f4] Stopping node
2016-03-04 17:03:06 CFY <manager> [manager_subnet_8f2f4] Deleting node
2016-03-04 17:03:07 CFY <manager> [manager_subnet_8f2f4.delete] Sending task 'azurecloudify.subnet.delete_subnet'
2016-03-04 17:03:07 CFY <manager> [manager_subnet_8f2f4.delete] Task started 'azurecloudify.subnet.delete_subnet'
2016-03-04 17:03:07 LOG <manager> [manager_subnet_8f2f4.delete] INFO: Deleting /tmp/manager_subnetmanager_subnet_8f2f4...
2016-03-04 17:03:07 LOG <manager> [manager_subnet_8f2f4.delete] ERROR: Exception raised on operation [azurecloudify.subnet.delete_subnet] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/subnet.py", line 54, in delete_subnet
    utils.clear_runtime_properties()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/utils.py", line 26, in clear_runtime_properties
    delete_runtime_properties_file()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/utils.py", line 217, in delete_runtime_properties_file
    os.remove(current_runtime_file_path)
OSError: [Errno 2] No such file or directory: '/tmp/manager_subnetmanager_subnet_8f2f4'
2016-03-04 17:03:07 CFY <manager> [manager_subnet_8f2f4.delete] Task failed 'azurecloudify.subnet.delete_subnet' -> [Errno 2] No such file or directory: '/tmp/manager_subnetmanager_subnet_8f2f4' [attempt 1/6]
2016-03-04 17:03:07 CFY <manager> [manager_resource_group_8dd0b] Stopping node
2016-03-04 17:03:08 CFY <manager> [manager_resource_group_8dd0b] Deleting node
2016-03-04 17:03:08 CFY <manager> [manager_resource_group_8dd0b.delete] Sending task 'azurecloudify.resourcegroup.delete_resource_group'
2016-03-04 17:03:08 CFY <manager> [manager_resource_group_8dd0b.delete] Task started 'azurecloudify.resourcegroup.delete_resource_group'
2016-03-04 17:03:08 LOG <manager> [manager_resource_group_8dd0b.delete] ERROR: Exception raised on operation [azurecloudify.resourcegroup.delete_resource_group] invocation
Traceback (most recent call last):
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-plugins-common/cloudify/decorators.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/resourcegroup.py", line 68, in delete_resource_group
    status_code = delete_current_resource_group(start_retry_interval, **kwargs)
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/resourcegroup.py", line 79, in delete_current_resource_group
    headers, location, subscription_id = auth.get_credentials()
  File "/home/tamirk/cfy_versions_root/3.3.1/ga/cloudify-azure-plugin/azurecloudify/auth.py", line 160, in get_credentials
    subscription_id = current_instance.runtime_properties['subscription_id']
KeyError: 'subscription_id'
2016-03-04 17:03:08 CFY <manager> [manager_resource_group_8dd0b.delete] Task failed 'azurecloudify.resourcegroup.delete_resource_group' -> 'subscription_id' [attempt 1/6]
2016-03-04 17:03:08 CFY <manager> [azure_token_066f9] Stopping node
2016-03-04 17:03:09 CFY <manager> [azure_token_066f9] Deleting node
2016-03-04 17:03:09 CFY <manager> 'uninstall' workflow execution succeeded
Workflow failed: Task failed 'azurecloudify.auth.initialize' -> 'access_token'
=============================================================
pre_blueprint_upload: execution id : 1457103486281_864100
=============================================================
blueprints_upload: execution id : 1457103486281_864100
Not using a Git Repository
=============================================================
pre_deployment_creation: execution id : 1457103486281_864100
=============================================================
pre_installation: execution id : 1457103486281_864100
=============================================================
post_installation: execution id : 1457103486281_864100
=============================================================
Deactivating virtualenv 'cfy_3_3_1ga_env'
